<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputloginpassword</name>
   <tag></tag>
   <elementGuidId>630f49a6-717f-4459-b56f-f82917cad1d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f16114f-ccfa-474c-8b4d-2f330e413b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>06d6df84-571d-443a-a39e-2bcacba73425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>28586f27-d4e5-4beb-bc8d-55bd51e45bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginpassword</value>
      <webElementGuid>1fc3cb9a-0722-4d84-a900-7f4c4398e23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginpassword&quot;)</value>
      <webElementGuid>3710391c-773b-4d09-ad2c-d35302153c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginpassword']</value>
      <webElementGuid>0ca26ec2-b43e-4650-b1bb-6ff6fd6bbcab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logInModal']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>27139efd-30a7-4b07-a6b4-e847a585c130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>c45f678f-51b7-4e79-81e0-becf89dff3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'loginpassword']</value>
      <webElementGuid>b20330fd-33a7-485f-ae70-d9a7ed836449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
