<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sauce Demo - Negative Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bda70eb7-6eb5-4457-b651-aedd8eb5c338</testSuiteGuid>
   <testCaseLink>
      <guid>263369eb-7e78-40b4-8752-bb3260d82734</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SauceDemo/Login Test - Negative - Locked User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e35cd29-130a-4f67-8547-b8b2fdbaf546</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbd99119-35a6-4ad1-9cb1-a2814ab7a977</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45f1a30f-2c27-4d37-8ba8-b7bc1e78d25b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SauceDemo/Login Test - Negative - Wrong User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68d55402-d88d-4efa-9613-b364892b4ab1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11d39fd9-5194-4c68-a549-b6385812a7fd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
